apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    svc: prometheus-ha
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 30900
