apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lunchtalk
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lunchtalk
  template:
    metadata:
      name: lunchtalk
      labels:
        app: lunchtalk
    spec:
      containers:
      - name: lunchtalk
        image: "micahhausler/k8s-lunchtalk:a84d3cf"
        ports:
        - name: web
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /metrics
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 10
